name: Test the solution

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.70.0
      - uses: actions/checkout@v2
      - name: Test
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: madraft::raft::tester=info,madraft::kvraft::tester=info,madraft::shard_ctrler::tester=info,madraft::shardkv::tester=info
        with:
          command: test
          args: --release --no-fail-fast
